title: "Future Tech"
description: "Многостраничный веб-сайт"
baseurl: "/future-tech"
url: ""

theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: assets/css
